#

apiVersion: v1
kind: Service
metadata:
  name: aaron-nodeport-service
  namespace: aaron-eks-activity

spec:
  type: NodePort
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 80                   # Service listens on port 80
      targetPort: 5678           # Pod container port
      nodePort: 30001            # Node's exposed port
