# Expose your Application using all 3 Services

apiVersion: v1
kind: Service
metadata:
  name: aaron-loadbalancer-service
  namespace: aaron-eks-activity
spec:
  type: LoadBalancer
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678