

apiVersion: v1
kind: Service
metadata:
  name: aaron-nginx-service
  namespace: aaron-eks-activity
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80