name: Build and Push Docker Image
on:
  push:
    paths:
      - 'product-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push image to ECR
        run: |
          IMAGE_URI=255945442255.dkr.ecr.us-east-1.amazonaws.com/product-service
          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI:dev-${{ github.sha }} ./product-service/k8s/dev
          docker push $IMAGE_URI:dev-${{ github.sha }}




  