name: Build Docker Image

on:
  push:
    branches: [ dev, test, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Docker Image
        run: |
          BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]')
          IMAGE_URI="123456789012.dkr.ecr.us-east-1.amazonaws.com/product-service:${BRANCH}-${GITHUB_SHA}"
          docker build -t $IMAGE_URI ./product-service
          docker push $IMAGE_URI
