


name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - dev
        - test
        - prod

jobs:
  terraform-create-and-destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: print environment
        run: | 
          echo "env choice is ${{ github.event.inputs.choice }}"
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init -backend-config=backend-${{ github.event.inputs.choice }}.config

      - name: Terraform workspace list
        run: terraform workspace list

      - name: Terraform workspace new environment and select
        run: |
          terraform workspace select ${{ github.event.inputs.choice }} || terraform workspace new ${{ github.event.inputs.choice }}
          terraform workspace list

      - name: Terraform plan
        run: terraform plan -var-file=infra/${{ github.event.inputs.choice }}.tfvars

      - name: Terraform apply
        run: terraform apply -var-file=infra/${{ github.event.inputs.choice }}.tfvars -auto-approve

      - name: Pause 3min to verify bucket creation
        run: sleep 180

      - name: Terraform destroy
        run: terraform destroy -var-file=infra/${{ github.event.inputs.choice }}.tfvars -auto-approve